#ifndef HARDWARE_CONFIG_H
#define HARDWARE_CONFIG_H

#define HW_WIFI_SSID "YOUR_WIFI_NAME"
#define HW_WIFI_PASSWORD "YOUR_WIFI_PASSWORD"

#define HW_BOOTSTRAP_HOST "192.168.x.x"
#define HW_BOOTSTRAP_PORT 5000
#define HW_BOOTSTRAP_PATH "/api/v1/hardware/bootstrap"

#define HW_HARDWARE_BOOTSTRAP_KEY "YOUR_BOOTSTRAP_KEY"

#define HW_ENTRY_SERVO_PIN 13
#define HW_EXIT_SERVO_PIN 12

#define SIMULATOR_KEY "YOUR_SIMULATOR_KEY"

#endif // HARDWARE_CONFIG_H